### ISSUE TITLE
The argument type 'dynamic' can't be assigned to the parameter type 'String'. 

### ISSUE THREAD

**Issue by noga-dev** [mmvergara/supabase-schema-dart-class-generator#5]
![image](https://github.com/mmvergara/supabase-schema-dart-class-generator/assets/2067558/c63ca4c1-b7d0-40d9-8ebe-201ae950e87f)

**Comment by mmvergara** [comment]
@noga-dev  Thanks for opening an issue, the tool is now updated try again, and let me know if you still have problems. 🙏

**Comment by noga-dev** [comment]
> @noga-dev Thanks for opening an issue, the tool is now updated try again, and let me know if you still have problems. 🙏

![image](https://github.com/mmvergara/supabase-schema-dart-class-generator/assets/2067558/0580109d-1036-49e4-b8bf-99ad5ed66d7d)

![image](https://github.com/mmvergara/supabase-schema-dart-class-generator/assets/2067558/36d88eac-7551-442f-be4e-50b552882394)

**Comment by mmvergara** [comment]
@noga-dev 
I think it's fixed. added [explicit type casting](https://github.com/mmvergara/supabase-schema-dart-class-generator/commit/091644c07feef975026ea0c5abfa18c0cc247a0e) which i didn't know is a convention and more importantly my IDE wasn't saying anything about that error.. do i have a old version of dart or something? weirdd.

**Comment by noga-dev** [comment]
![image](https://github.com/mmvergara/supabase-schema-dart-class-generator/assets/2067558/4a2ae5c4-86c7-44da-9fd2-604263650f62)

**Comment by mmvergara** [comment]
>  more importantly my IDE wasn't saying anything about that error.. do i have a old version of dart or something? weirdd.

need this on pubspec.yml
```yml
analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true
```

**Comment by noga-dev** [comment]
Fwiw I'm on 3.22.2

**Comment by noga-dev** [comment]
my analysis_options.dart:

```yaml
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  # errors:
    # invalid_annotation_target: ignore
  exclude:
    - "lib/**.g.dart"
    - "lib/**.f.dart"
    - "lib/gen/**.dart"
  warnings:
    # unused_element: ignore
  errors:
    unused_element: false
  
custom_lint:
  rules:

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    public_member_api_docs: ignore
    
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
```
